a=(float(input("Enter a float value : ")))
b=(float(input("Enter second float value : ")))
print("Addition:", a,"+",b,"= ", a+b)
print("Subtraction : ",a,"-",b,"= ", a-b)
print("Product : ", a,"*",b,"= ", a*b)
print("Division : ", a,"/",b,"= ", a/b)
print("Modulus : ", a,"%",b,"= ", a%b)
print("Floor Division : ", a,"//",b,"= ", a//b)
